"""Behavior retained from older PRs, exercised through the actual hooks/templates."""
import json
import shutil
import unittest

from test_stability import Fixture, PLATFORM


class StopHookTests(Fixture):
    def stop(self, expected=0):
        return self.run_cmd('bash', PLATFORM / 'hooks/stop-check.sh', expected=expected)

    def test_bin_check_without_package_json_and_cached_second_stop(self):
        (self.repo / 'source').write_text('modified\n')
        self.stop()
        self.stop()
        self.assertEqual(self.calls(), 1)

    def test_bin_check_failure_blocks_stop(self):
        self.write_check('echo deliberate-failure\nexit 7\n')
        self.assertIn('deliberate-failure', self.stop(expected=2).stdout)
        self.check('--status', expected=1)

    def test_clean_tree_with_unpublished_commits_is_checked(self):
        self.setup_remote()
        self.run_cmd('git', 'branch', '--set-upstream-to=origin/main')
        (self.repo / 'source').write_text('committed\n')
        self.commit()
        self.stop()
        self.assertEqual(self.calls(), 1)

    def test_clean_tree_at_upstream_does_not_run_check(self):
        self.setup_remote()
        self.run_cmd('git', 'branch', '--set-upstream-to=origin/main')
        self.stop()
        self.assertEqual(self.calls(), 0)


@unittest.skipUnless(shutil.which('bun'), 'Bun is required to execute the repository hygiene template')
class HygieneTemplateTests(Fixture):
    def hygiene(self, base):
        module = PLATFORM / 'templates/scripts/checks/hygiene.ts'
        script = self.base / 'check-template.ts'
        script.write_text(
            f'import {{checkHygiene}} from {json.dumps(str(module))};\n'
            'console.log(JSON.stringify(checkHygiene({cwd: process.argv[2], baseRef: process.argv[3]})));\n')
        result = self.run_cmd(shutil.which('bun'), script, self.repo, base)
        return json.loads(result.stdout)

    def commit_message(self, message):
        self.run_cmd('git', 'add', '.')
        self.run_cmd('git', 'commit', '--allow-empty', '-qm', message)

    def test_actual_history_flags_tool_trailer_and_generated_with(self):
        base = self.run_cmd('git', 'rev-parse', 'HEAD').stdout.strip()
        self.commit_message('fix: update behavior\n\nCo-authored-by: Claude <noreply@anthropic.com>')
        self.commit_message('fix: update another behavior\n\nGenerated with a tool')
        result = self.hygiene(base)
        self.assertEqual(result['commitsChecked'], 2)
        self.assertEqual([f['code'] for f in result['findings']],
                         ['trailer-attribution', 'trailer-attribution'])

    def test_plain_history_and_nonphrase_are_clean_but_source_tokens_are_not(self):
        base = self.run_cmd('git', 'rev-parse', 'HEAD').stdout.strip()
        self.commit_message('fix: regenerate data\n\nData regenerated with a new seed')
        self.assertEqual(self.hygiene(base)['findings'], [])
        (self.repo / 'src').mkdir()
        (self.repo / 'src/example.ts').write_text('// Generated by codex\n')
        self.commit_message('fix: add example')
        findings = self.hygiene(base)['findings']
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0]['code'], 'forbidden-token')
        self.assertEqual(findings[0]['where'], 'src/example.ts:1')
